# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Instalação

Para instalar o NumPy, você pode usar o pip, que é o gerenciador de pacotes do Python.

```python
pip install numpy
```

## Arrays

Um array é uma estrutura de dados que armazena valores do mesmo tipo. Em Python, isso é uma grande vantagem porque economiza espaço e permite operações mais eficientes. Vamos criar um array.



In [ ]:
!pip3 install numpy

In [ ]:
import numpy as np

# criação de um array
array_inteiros = np.array([1, 2, 3, 4, 5])

print(array_inteiros)

### Conhecendo um array: indexação e slicing

In [ ]:
# pegando/printando a primeira posição
print(array_inteiros[0])

1


In [ ]:
# printando a última posição do array
print(array_inteiros[-1]) 
# ou
print(array_inteiros[4])

5
5


In [ ]:
# aplicando slicing para pegar uma parte do array
# [inicio:fim] -> inicio até fim, sendo o ínicio um valor incluso e fim um valor excluso

print(array_inteiros[1:4])

[2 3 4]


In [ ]:
# array[0:-1] -> vai do inicio até o final do array, sem adicionar a
# última posição, pois ela é exclusa
print(array_inteiros[0:-1])

[1 2 3 4]


In [12]:
print(array_inteiros)

[1 2 3 4 5]


In [ ]:
# array[inicio:fim:step] -> vai mostrar os elementos do inicio, ao fim, excluindo o última valor
# sempre 'pulando' o número de casas estabelecido no step(passo)

print(array_inteiros[0:-1:3])

[1 4]


In [ ]:
# para realizar a inclusão do último elemento, faremos da seguinte forma
# ao adicionar o -1 antre os : sempre exclui o última valor

print(array_inteiros[0::2])

[1 3 5]


In [17]:
# outra forma de pegar o array desde o ínicio, é so deixar o primeiro valor em branco também 
print(array_inteiros[::2])

[1 3 5]


In [19]:
# como o valor padrão do step é 1, caso deixamos em branco ou nao mencionarmos ele, 
# o mesmo assume que seja 1
print(array_inteiros[::])
print(array_inteiros[:])

[1 2 3 4 5]
[1 2 3 4 5]


In [20]:
# para imprimir de maneira inversa, basta colocar no step o valor -1

print(array_inteiros[::-1])

[5 4 3 2 1]
